title: Blue Harvest
description: Welcome page for working group Blue Harvest
theme: just-the-docs

url: https://gfse.github.io/blue-harvest-pages

aux_links:
  Repo: https://github.com/GfSE/blue-harvest-pages
